
---
##  perform Kernel patching on RHEl/CentOS Server
## 
## Desruptive patch (kernel) 

- name: perform Kernel patching on RHEl/CentOS Server
  hosts: all
  user: ec2-user
  become: true
  any_errors_fatal: false
  vars:
    random_number: "{{ 10000 | random }}" 

  tasks:
    - name: Generate a random name for the temp folder
      set_fact:
        tempdir: "temp{{ random_number }}"

    - name: Create the temp folder on remote
      file:
        path: "/tmp/{{ tempdir }}"
        state: directory

    - name: Copy precheck script file from local to remote
      copy: src="/home/ec2-user/pre-check.sh" dest="/tmp/{{ tempdir }}/pre-check.sh" mode=0777
    - name: Run pre-check.sh before patching to capture data
      command: "sh /tmp/{{ tempdir }}/pre-check.sh"
      ignore_errors: yes
      register: prechecks
    - action:
       module: copy
       content: "{{ prechecks.stdout }}"
       dest : /tmp/{{ inventory_hostname }}_prechecks.txt

    # purpose of this task to check if application is running or stopped
    - name:  verify application/database processes are not running
      shell: if ps -eaf | egrep 'apache|http'|grep -v grep > /dev/null ;then echo 'process_running';else echo 'process_not_running';fi
      ignore_errors: true
      register: app_process_check

    # this task is decision,play will fail/quit,if application is running
    - name:  decision point to start patching
      fail: msg="{{ inventory_hostname }} have running Application.Please stop the application first, then attempt patching."
      when: app_process_check.stdout == "process_running"

    # this task will upgrade/install the rpm's if application is not running
    - name:  upgrade all kernel packages on the server
      yum:
       name="kernel"
       state=latest
      when: app_process_check.stdout == "process_not_running" and ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
      register: yum_update

    # this task is to check if kernel update happend and system needs reboot ot not
    - name: check if reboot required after kernel update.
      shell: KERNEL_NEW=$(rpm -q --last kernel |head -1 | awk '{print $1}' | sed 's/kernel-//'); KERNEL_NOW=$(uname -r); if [[ $KERNEL_NEW != $KERNEL_NOW ]]; then echo "reboot_needed"; else echo "reboot_not_needed"; fi
      ignore_errors: true
      register: reboot_required

    # this task is to restart the system
    - name: restart system
      command: shutdown -r +1  "Rebooting System After Patching"
      async: 0
      poll: 0
      when: reboot_required.stdout == "reboot_needed"
      register: reboot_started
      ignore_errors: true

    # this task is to wait for 3 minutues for system to come up after the reboot
    - name: pause for 180 secs
      pause:
        minutes: 3

    # this task is to confirm,system is up and responding to ssh
    - name: check if system responding to ssh
      local_action:
        module: wait_for
          host={{ inventory_hostname }}
          port=22
          delay=15
          timeout=300
          state=started
      when: reboot_started|changed
