---
- hosts: all
  become: yes
  become_method: enable
  vars: 
   ansible_python_interpreter: /usr/bin/python
  tasks:
  - name: Create a file
    file: 
     path: "/etc/nag.txt"
     state: touch
  
